title: Enggarukei's Book Reviews
description: Catatan, renungan, dan kutipan dari buku-buku yang pernah saya baca.
author: Enggarukei
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

minima:
  navigation:
    - title: "Beranda"
      url: "/"
    - title: "Tentang"
      url: "/tentang"
    - title: "Kutipan"
      url: "/kutipan"
    - title: "Kategori"
      url: "/kategori"

sass:
  style: compressed

include:
  - _includes/head-custom.html
